openapi: 3.0.0
info:
  title: sampl_api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /sample/users:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-sample-api-users
    parameters: []
components:
  schemas: {}
